### ISSUE TITLE
Вот такое

### ISSUE THREAD

**Issue by ramir1** [dbelyaeff/cogear#2]
на странице 
http://new.cogear.ru/user/login

Error
Error in file /home/cogear/data/www/new.cogear.ru/engine/User/Object.php was found at line 118:

```
Trying to get property of non-object
```

**Comment by JiLiZART** [comment]
Небольшой баг с сессией, немного терпения, скоро всё поправится.

**Comment by dbelyaeff** [comment]
Это не с сессией баг. Решено.

**Comment by icedragon** [comment]
Получил багу что пользователь не может зарегистрироваться (ничего не происходит, и  без вывода ошибки), просмотрев исходники я вижу что когда идет проверка на существование пользователя (User_Validate_Login) и email (User_Validate_Email) мне возвращается обратный результат - если пользователь не зарегистрирован то false а если зарегистрирован то true, а должно быть наоборот.

User_Validate_Login:
было  return !($user->find() && $this->element->addError(t('Login is already taken!'))) ? FALSE : TRUE;
поправил на return ($user->find() && $this->element->addError(t('Login is already taken!'))) ? FALSE : TRUE;

User_Validate_Email:
было return !($user->find() && $this->element->addError(t('Email is already taken!'))) ? FALSE : TRUE;
поправил на return ($user->find() && $this->element->addError(t('Email is already taken!'))) ? FALSE : TRUE;
