### ISSUE TITLE
Расширение иерархии файловой системы

### ISSUE THREAD

**Issue by slider23** [dbelyaeff/cogear#3]
Дублирую здесь, чтобы не потерялось.

http://cogear.ru/gear-643.html#comment-11396 :
Я, в общем, вот что предлагаю. Сделать иерархическую файловую систему, как в Кохане. Т.е. если положить файлик в /sites/domain.com/gears/Pages/templates/page.php, то для отображения будет браться именно он, а не то, что в engine. И чтобы при этом оформлять Pages как шестеренку в sites не надо было. То же относится к папке css и к другим папкам и файлам (надо определиться к каким именно. В идеале ко всем, но вопрос, будет ли это удобно движку).

Цель - не давать юзерам править файты в engines, не затрудняя при этом особо жизнь.

**Comment by JiLiZART** [comment]
Так то эта концепция уже используется, для шестерёнок. Для шаблонов тоже не трудно сделать, ну и всего остального тоже.

**Comment by slider23** [comment]
Сейчас минимальный объект, который юзается в "слоеном пироге" - шестеренка, а не файл. 
Чтобы изменить один символ в отображении страницы пользователю надо переопределить всю шестеренку Pages целиком, со всем функционалом. А если она проапдейтится, новым функционалом, который нужен пользователю ? Ему надо хранить лог того, что он в ней поменял, чтобы накатить эти изменения на измененную версию ?

**Comment by JiLiZART** [comment]
в скором времени будет и для файлов
